-- Migration: Add super_prompts table for storing optimized prompts
-- Date: 2025-11-24

-- Create super_prompts table
CREATE TABLE IF NOT EXISTS "public"."super_prompts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "generated_prompt" "text" NOT NULL,
    "ai_model" "text" NOT NULL DEFAULT 'openai'::"text",
    "questions" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "super_prompts_pkey" PRIMARY KEY ("id")
);

-- Add foreign key constraint (if it doesn't exist)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'super_prompts_user_id_fkey'
    ) THEN
        ALTER TABLE ONLY "public"."super_prompts"
            ADD CONSTRAINT "super_prompts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
    END IF;
END $$;

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS "idx_super_prompts_user_id" ON "public"."super_prompts" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_super_prompts_ai_model" ON "public"."super_prompts" USING "btree" ("ai_model");
CREATE INDEX IF NOT EXISTS "idx_super_prompts_created_at" ON "public"."super_prompts" USING "btree" ("created_at");

-- Enable RLS
ALTER TABLE "public"."super_prompts" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for super_prompts (if it doesn't exist)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename = 'super_prompts' 
        AND policyname = 'Users manage their own super prompts'
    ) THEN
        CREATE POLICY "Users manage their own super prompts" ON "public"."super_prompts" 
            FOR ALL USING (("auth"."uid"() = "user_id")) 
            WITH CHECK (("auth"."uid"() = "user_id"));
    END IF;
END $$;

-- Create function to update super_prompts updated_at
CREATE OR REPLACE FUNCTION "public"."update_super_prompts_updated_at"()
RETURNS "trigger" AS $$
BEGIN
    NEW."updated_at" = now();
    RETURN NEW;
END;
$$ LANGUAGE "plpgsql";

-- Create trigger for super_prompts updated_at (if it doesn't exist)
DROP TRIGGER IF EXISTS "update_super_prompts_updated_at" ON "public"."super_prompts";
CREATE TRIGGER "update_super_prompts_updated_at" 
    BEFORE UPDATE ON "public"."super_prompts" 
    FOR EACH ROW EXECUTE FUNCTION "public"."update_super_prompts_updated_at"();

-- Grant permissions
GRANT ALL ON TABLE "public"."super_prompts" TO "anon";
GRANT ALL ON TABLE "public"."super_prompts" TO "authenticated";
GRANT ALL ON TABLE "public"."super_prompts" TO "service_role";

-- Add comments
COMMENT ON TABLE "public"."super_prompts" IS 'Stores optimized prompts generated by AI models';
COMMENT ON COLUMN "public"."super_prompts"."user_id" IS 'Reference to the user who owns this super prompt';
COMMENT ON COLUMN "public"."super_prompts"."generated_prompt" IS 'The optimized prompt generated by AI (can store large strings)';
COMMENT ON COLUMN "public"."super_prompts"."ai_model" IS 'The AI model used to generate the prompt (openai, claude, gemini, grok)';
COMMENT ON COLUMN "public"."super_prompts"."questions" IS 'Stringified JSON of questions object (restorative, constraints, preferences, goal)';

